version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  target-branch: development
  reviewers:
  - echarrod
  - davidgrayston
  assignees:
  - echarrod
