version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    target_branch: "development"

    default_reviewers:
      - "echarrod"
      - "davidgrayston"
      - "MrBurtyyy"

    default_assignees: ["echarrod"]
